import random

adjectives = [
    "happy", "sad", "bright", "dark", "loud", "quiet", "angry", "calm", "fast", "slow",
    "big", "small", "hot", "cold", "tall", "short", "heavy", "light", "strong", "weak",
    "beautiful", "ugly", "clean", "dirty", "healthy", "sick", "thin", "thick", "rich", "poor",
    "young", "old", "funny", "serious", "kind", "cruel", "brave", "cowardly", "wise", "foolish",
    "smart", "dumb", "simple", "complex", "honest", "dishonest", "generous", "selfish", "polite", "rude",
    "creative", "boring", "loving", "hateful", "adventurous", "cautious", "active", "lazy", "jolly", "grumpy",
    "spacious", "cramped", "bright", "dull", "mysterious", "obvious", "delicious", "disgusting", "gentle", "harsh",
    "vivid", "pale", "wild", "tame", "flexible", "rigid", "fragile", "tough", "helpful", "useless",
    "noisy", "peaceful", "exciting", "boring", "lively", "lifeless", "confident", "insecure", "eager", "reluctant",
    "attractive", "repulsive", "familiar", "strange", "caring", "indifferent", "daring", "timid", "charming", "repulsive",
    "lucky", "unlucky", "glamorous", "dull", "productive", "unproductive", "vibrant", "dull", "productive", "unproductive",
    "helpless", "competent", "shy", "outgoing", "sincere", "insincere", "respectful", "disrespectful", "confused", "clear",
    "ambitious", "lazy", "innocent", "guilty", "curious", "indifferent", "flexible", "inflexible", "humble", "arrogant",
    "determined", "indecisive", "fierce", "gentle", "elegant", "clumsy", "thoughtful", "thoughtless", "cooperative", "uncooperative",
    "loyal", "disloyal", "sensible", "nonsensical", "experienced", "inexperienced", "optimistic", "pessimistic", "tolerant", "intolerant",
    "trustworthy", "untrustworthy", "rational", "irrational", "responsible", "irresponsible", "passionate", "apathetic", "talented", "untalented",
    "creative", "uncreative", "witty", "dull", "grateful", "ungrateful", "diligent", "lazy", "independent", "dependent",
    "daring", "timid", "efficient", "inefficient", "faithful", "faithless", "diligent", "negligent", "resourceful", "unresourceful",
    "thoughtful", "thoughtless", "exuberant", "depressed", "accomplished", "incomplete", "imaginative", "unimaginative", "cautious", "reckless",
    "responsive", "unresponsive", "adventurous", "cautious", "practical", "impractical", "sensible", "nonsensical", "resilient", "fragile",
    "amicable", "hostile", "graceful", "awkward", "distinguished", "ordinary", "unique", "common", "assertive", "passive",
    "brilliant", "dull", "vocal", "quiet", "prosperous", "struggling", "celebrated", "unknown", "efficient", "inefficient",
    "mature", "immature", "invincible", "vulnerable", "loyal", "disloyal", "persistent", "quitting", "prudent", "reckless",
    "responsive", "unresponsive", "energetic", "sluggish", "graceful", "awkward", "humorous", "serious", "shrewd", "naive",
    "successful", "unsuccessful", "charismatic", "bland", "complex", "simple", "magnificent", "ordinary", "vivid", "dull",
    "perceptive", "oblivious", "accomplished", "incomplete", "perceptive", "oblivious", "eager", "reluctant", "charismatic", "bland",
]

nouns = [
    "apple", "banana", "orange", "dog", "cat", "bird", "tree", "flower", "car", "book",
    "house", "table", "chair", "computer", "phone", "pencil", "pen", "river", "mountain", "ocean",
    "sun", "moon", "star", "cloud", "rain", "snow", "wind", "fire", "earth", "sky",
    "friend", "family", "teacher", "student", "doctor", "engineer", "actor", "artist", "singer", "writer",
    "scientist", "politician", "chef", "athlete", "baby", "child", "adult", "parent", "grandparent", "neighbor",
    "city", "village", "country", "continent", "island", "lake", "forest", "desert", "jungle", "cave",
    "school", "college", "university", "hospital", "library", "park", "zoo", "market", "store", "restaurant",
    "airport", "train", "bus", "ship", "bicycle", "motorcycle", "helicopter", "rocket", "submarine", "truck",
    "camera", "television", "radio", "music", "movie", "game", "sport", "art", "history", "science",
    "mathematics", "language", "culture", "religion", "politics", "economy", "society", "nature", "environment", "technology",
    "space", "time", "love", "happiness", "peace", "freedom", "justice", "faith", "hope", "dream",
    "success", "failure", "truth", "wisdom", "courage", "strength", "patience", "kindness", "generosity", "humility",
    "passion", "creativity", "imagination", "curiosity", "ambition", "friendship", "loyalty", "laughter", "tears", "memory",
    "dream", "idea", "plan", "goal", "challenge", "problem", "solution", "victory", "defeat", "adventure",
    "journey", "experience", "achievement", "discovery", "invention", "celebration", "ceremony", "holiday", "tradition", "custom",
    "culture", "history", "legend", "myth", "folklore", "fable", "fairytale", "story", "poem", "song",
    "dance", "painting", "sculpture", "architecture", "design", "recipe", "meal", "drink", "dessert", "snack",
    "clothing", "shoes", "jewelry", "accessory", "gadget", "tool", "instrument", "appliance", "furniture", "artifact",
    "treasure", "coin", "gem", "currency", "ticket", "passport", "certificate", "document", "letter", "message",
    "map", "flag", "symbol", "sign", "code", "number", "letter", "word", "sentence", "paragraph",
    "chapter", "verse", "book", "novel", "story", "poem", "essay", "article", "report", "speech",
    "lecture", "presentation", "movie", "show", "play", "concert", "event", "celebration", "festival", "ceremony",
    "wedding", "birthday", "anniversary", "holiday", "vacation", "trip", "journey", "adventure", "expedition", "exploration",
    "discovery", "research", "experiment", "theory", "hypothesis", "law", "principle", "formula", "equation", "variable",
    "constant", "quantity", "measurement", "observation", "analysis", "interpretation", "conclusion", "recommendation", "application",
    "solution", "problem", "challenge", "task", "goal", "objective", "mission", "vision", "dream", "ambition",
    "aspiration", "desire", "hope", "faith", "belief", "doubt", "question", "answer", "query", "inquiry",
    "investigation", "research", "discovery", "innovation", "invention", "creation", "imagination", "inspiration", "motivation", "enthusiasm",
]

def get():
    return random.choice(adjectives).capitalize()+' '+random.choice(nouns).capitalize()
